base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>', views.detail, name='detail'),
    path('create-room/', views.createRoom, name='create_room'),
    path('update-room/<int:pk>', views.updateRoom, name='update_room'),
    path('delete-room/<int:pk>', views.deleteRoom, name='delete_room'),
]

studyBud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    # participants =
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-updated','-created']

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.body[:50]

base/forms.py
from django.forms import ModelForm
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Room, Topic
from .forms import RoomForm
from django.db.models import Q
# Create your views here.
def home(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    print(q)
    rooms = Room.objects.filter(Q(topic__name__contains=q) | Q(name__contains=q)| Q(description__contains=q))
    room_count = rooms.count()
    topics = Topic.objects.all()
    context = {'rooms':rooms, 'topics':topics,'room_count':room_count}
    return render(request, 'base/home.html', context)


def detail(request, pk):
    return HttpResponse('Not impemented yet')

def createRoom(request):
    form = RoomForm()
    if request.method == 'POST':
        form = RoomForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:home')
    context = {'form':form}
    return render(request, 'base/room_form.html',context)

def updateRoom(request,pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    if request.method=='POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('base:home')
    context = {'form':form}
    return render(request, 'base/room_form.html',context)

def deleteRoom(request,pk):
    room = Room.objects.get(pk=pk)
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
    context = {'obj':room}
    return render(request, 'base/deleteTemplate.html',context)

base/templates/base/deleteTemplate.html
{% extends 'base/main.html' %}

{% block content %}
    <h2>Are you sure you want to delete {{ obj }}</h2>
    <form method="post" action="">
        {% csrf_token %}
        <a href="{{request.META.HTTP_REFERER}}">Go back</a>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

base/templates/base/home.html
{% extends 'base/main.html' %}
{% block content %}


<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 5fr;
    }
</style>


<div class="home-container">

    <div>
        <h3>Browse Topics</h3>
        <hr>
            <div>
                <a href="{% url 'base:home' %}">All</a>
            </div>
        {% for topic in topics %}
            <div>
                <a href="{% url 'base:home' %}?q={{ topic.name }}">{{ topic }}</a>
            </div>
        {% endfor %}
    </div>
    <div>
        <h5>Found rooms: {{ room_count }}</h5>
        <a href="{% url 'base:create_room' %}">Create room</a>
    <hr>
    {% for room in rooms %}
        <div>
            <a href="{% url 'base:update_room' room.id %}">Update</a>
            <a href="{% url 'base:delete_room' room.id %}">Delete</a><br>
            <span>@{{ room.host.username }}</span>
            <h2><a href="{% url 'base:detail' room.id%}">{{ room.name }}</a> </h2>
            <small>{{ room.topic }}</small>
            <hr>
        </div>

    {% endfor %}
    </div>

</div>

{% endblock %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'base/topPanel.html' %}
    <title>Epic shit</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

base/templates/base/room_form.html
{% extends 'base/main.html' %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

base/templates/base/topPanel.html
<h1><a href="{% url 'base:home' %}">Go home</a></h1>

<form action="{% url 'base:home' %}">
    <input type="text" name="q" placeholder="Search rooms...">
</form>
<hr>